version: "3.7"

services:
  database: 
    image: mysql
    container_name: db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes: 
      - mysqldata:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hubla
    networks:
      - node-network
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: backend
    tty: true
    networks:
      - node-network
    ports:
      - "3333:3333"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    tty: true
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on: 
      - backend
     
networks:
  node-network:
    driver: bridge

volumes: 
  mysqldata:
    driver: local
