version: "3.7"

services:
  database: 
    image: mysql
    container_name: db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hubla
    networks:
      - node-network
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  app:
    build: ./backend
    container_name: app
    tty: true
    networks:
      - node-network
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/app
    depends_on:
      database:
        condition: service_healthy

networks:
  node-network:
    driver: bridge
